FROM microsoft/iis:windowsservercore-ltsc2016

RUN mkdir C:\Site 

RUN powershell -NoProfile -Command \ 
    Add-WindowsFeature -Name Web-ASP-Net45 
RUN powershell -NoProfile -Command \ 
    Import-module IISAdministration; \ 
    New-IISSite -Name "Site" -PhysicalPath C:\site -BindingInformation "*:8000:"

WORKDIR /Site 
COPY publish /Site
COPY InitContainer.ps1 /Site

EXPOSE 8000
ENTRYPOINT powershell .\InitContainer.ps1
