name 'PasswordService'
maintainer 'Brian Denicola'
maintainer_email 'bjd145@yahoo.com'
license 'all_rights'
description 'Installs/Configures PasswordService'
long_description 'Installs/Configures PasswordService'
version '0.2.2'

depends 'sql_server', '~> 2.4.0'
depends 'iis', '~> 4.1.1'